require 'active_support/all'
require './day'
require './coordinate_decorator'
require './coordinate'
require './twenty_five'
require './twenty_four'
# require './twenty_three'
require './twentytwo'
require './twentyone'
require './eighteen'
require './sixteen'
require './fifteen'
# require './fourteen.rb'
require './thirteen'
# require './twelve.rb'
require './eleven'
require './ten'
require './nine'
require './eight'
require './seven'
require './six'
# require './six_optimised.rb'
require './five_propper'
# require './five.rb'
require './four'
require './three'
require './two'
require './one'

Day.run
