require 'active_support/all'
require './day.rb'
require './fourteen.rb'
require './thirteen.rb'
# require './twelve.rb'
require './eleven.rb'
require './ten.rb'
require './nine.rb'
require './eight.rb'
require './seven.rb'
require './six.rb'
# require './six_optimised.rb'
require './five_propper.rb'
# require './five.rb'
require './four.rb'
require './three.rb'
require './two.rb'
require './one.rb'

Day.run
